#PBS -q mindscope
#PBS -l walltime=12:00:00
#PBS -l nodes=5:ppn=32
#PBS -N lr2_g8_8_test500ms_inh_lif_syn_z108
#PBS -r n
#PBS -j oe
#PBS -o output_lr2_g8_8_test500ms_inh_lif_syn_z108/lr2_g8_8_test500ms_inh_lif_syn_z108.out
#PBS -m a
cd $PBS_O_WORKDIR

export LD_PRELOAD=/usr/lib64/libstdc++.so.6
export PATH=/shared/utils.x86_64/hydra-3.0.4/bin/:$PATH

mpiexec -np 160 nrniv -mpi run_lr2_g8_8_test500ms_inh_lif_syn_z108.py > output_lr2_g8_8_test500ms_inh_lif_syn_z108/log.txt
